version: "3.3"

services:
  efb:
    image: ghcr.io/jiz4oh/efb
    container_name: efb
    network_mode: host
    volumes:
      - .:/data
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
